# Site settings
title: cv,
tag_text: cv
description: markdown-cv is a simple template to list all your accomplishments in a readable Markdown file. It uses CSS to style your text into a web page and a beautiful looking PDF.

# Build settings
markdown: kjhealy
exclude: ["README.md"]
sass:
  style: compressed
